'use client';
export const dynamic='force-static';
import {useEffect,useRef,useState} from 'react';
import {Guitar,Mic,Music2,Search,Sparkles,Square,Volume2} from 'lucide-react';
import {formatCopy,getCopy,languages,type Language} from './i18n';
type Chord={name:string;full:string;frets:number[];fingers:number[];notes:string[];baseFret?:number};
const featuredChords:Chord[]=[
{name:'C',full:'C-dur',frets:[-1,3,2,0,1,0],fingers:[0,3,2,0,1,0],notes:['C','E','G']},{name:'G',full:'G-dur',frets:[3,2,0,0,0,3],fingers:[2,1,0,0,0,3],notes:['G','B','D']},{name:'D',full:'D-dur',frets:[-1,-1,0,2,3,2],fingers:[0,0,0,1,3,2],notes:['D','F#','A']},{name:'Am',full:'A-moll',frets:[-1,0,2,2,1,0],fingers:[0,0,2,3,1,0],notes:['A','C','E']},{name:'Em',full:'E-moll',frets:[0,2,2,0,0,0],fingers:[0,2,3,0,0,0],notes:['E','G','B']},{name:'E',full:'E-dur',frets:[0,2,2,1,0,0],fingers:[0,2,3,1,0,0],notes:['E','G#','B']},{name:'A',full:'A-dur',frets:[-1,0,2,2,2,0],fingers:[0,0,1,2,3,0],notes:['A','C#','E']},{name:'F',full:'F-dur',frets:[1,3,3,2,1,1],fingers:[1,3,4,2,1,1],notes:['F','A','C']}];
const pitchNames=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const templates:[string,number[]][]=pitchNames.flatMap((name,root)=>[[name,[root,(root+4)%12,(root+7)%12]],[`${name}m`,[root,(root+3)%12,(root+7)%12]]] as [string,number[]][]);
const roots=['C','C# / Db','D','D# / Eb','E','F','F# / Gb','G','G# / Ab','A','A# / Bb','B'];
const noteNames=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const diagramQualities=[
{symbol:'',label:'dur',ints:[0,4,7],e:[0,2,2,1,0,0],a:[-1,0,2,2,2,0],ef:[0,3,4,2,1,1],af:[0,1,2,3,4,1]},
{symbol:'m',label:'moll',ints:[0,3,7],e:[0,2,2,0,0,0],a:[-1,0,2,2,1,0],ef:[0,3,4,1,1,1],af:[0,1,3,4,2,1]},
{symbol:'7',label:'dominant 7',ints:[0,4,7,10],e:[0,2,0,1,0,0],a:[-1,0,2,0,2,0],ef:[0,3,1,2,1,1],af:[0,1,3,1,4,1]},
{symbol:'maj7',label:'maj 7',ints:[0,4,7,11],e:[0,2,1,1,0,0],a:[-1,0,2,1,2,0],ef:[0,3,2,2,1,1],af:[0,1,3,2,4,1]},
{symbol:'m7',label:'moll 7',ints:[0,3,7,10],e:[0,2,0,0,0,0],a:[-1,0,2,0,1,0],ef:[0,3,1,1,1,1],af:[0,1,3,1,2,1]},
];
const generatedChords:Chord[]=pitchNames.flatMap((root,rootIndex)=>diagramQualities.map(q=>{const eFret=(rootIndex-4+12)%12,aFret=(rootIndex-9+12)%12,useE=eFret<=aFret,fret=useE?eFret:aFret,shape=useE?q.e:q.a,fingers=useE?q.ef:q.af;return{name:`${root}${q.symbol}`,full:`${root}-${q.label}`,frets:shape.map(x=>x<0?-1:x+fret),fingers,notes:q.ints.map(i=>noteNames[(rootIndex+i)%12]),baseFret:fret>=2?fret:1}}));
const chords:Chord[]=[...featuredChords,...generatedChords.filter(c=>!featuredChords.some(featured=>featured.name===c.name))];
const qualities=[
{id:'maj',label:'Dur',symbol:'',ints:[0,4,7],scales:['Jonisk (dur)','Durpentatonisk','Lydisk']},{id:'min',label:'Moll',symbol:'m',ints:[0,3,7],scales:['Eolisk (naturlig moll)','Mollpentatonisk','Dorisk']},{id:'7',label:'Dominant 7',symbol:'7',ints:[0,4,7,10],scales:['Mixolydisk','Dominant pentatonisk','Altererad (spänning)']},{id:'maj7',label:'Maj 7',symbol:'maj7',ints:[0,4,7,11],scales:['Jonisk (dur)','Lydisk','Durpentatonisk']},{id:'m7',label:'Moll 7',symbol:'m7',ints:[0,3,7,10],scales:['Dorisk','Eolisk','Mollpentatonisk']},{id:'dim',label:'Förminskat',symbol:'dim',ints:[0,3,6],scales:['Hel-halv-diminished','Lokrisk','Symmetrisk diminished']},{id:'dim7',label:'Förminskat 7',symbol:'dim7',ints:[0,3,6,9],scales:['Hel-halv-diminished','Diminished arpeggio']},{id:'aug',label:'Förstorat',symbol:'aug',ints:[0,4,8],scales:['Heltonsskala','Lydisk augmented']},{id:'sus2',label:'Sus 2',symbol:'sus2',ints:[0,2,7],scales:['Jonisk','Mixolydisk','Durpentatonisk']},{id:'sus4',label:'Sus 4',symbol:'sus4',ints:[0,5,7],scales:['Mixolydisk','Jonisk','Durpentatonisk']},{id:'6',label:'Dur 6',symbol:'6',ints:[0,4,7,9],scales:['Jonisk','Durpentatonisk','Lydisk']},{id:'m6',label:'Moll 6',symbol:'m6',ints:[0,3,7,9],scales:['Dorisk','Melodisk moll']},{id:'9',label:'Dominant 9',symbol:'9',ints:[0,4,7,10,2],scales:['Mixolydisk','Bebop dominant']},{id:'maj9',label:'Maj 9',symbol:'maj9',ints:[0,4,7,11,2],scales:['Jonisk','Lydisk']},{id:'m9',label:'Moll 9',symbol:'m9',ints:[0,3,7,10,2],scales:['Dorisk','Eolisk']},{id:'add9',label:'Add 9',symbol:'add9',ints:[0,4,7,2],scales:['Jonisk','Durpentatonisk']},{id:'11',label:'Dominant 11',symbol:'11',ints:[0,4,7,10,2,5],scales:['Mixolydisk','Bebop dominant']},{id:'13',label:'Dominant 13',symbol:'13',ints:[0,4,7,10,2,9],scales:['Mixolydisk','Bebop dominant']}];
const scaleIntervals:Record<string,number[]>={'Jonisk (dur)':[0,2,4,5,7,9,11],Jonisk:[0,2,4,5,7,9,11],Durpentatonisk:[0,2,4,7,9],Lydisk:[0,2,4,6,7,9,11],'Eolisk (naturlig moll)':[0,2,3,5,7,8,10],Eolisk:[0,2,3,5,7,8,10],Mollpentatonisk:[0,3,5,7,10],Dorisk:[0,2,3,5,7,9,10],Mixolydisk:[0,2,4,5,7,9,10],'Dominant pentatonisk':[0,2,4,7,10],'Altererad (spänning)':[0,1,3,4,6,8,10],'Hel-halv-diminished':[0,2,3,5,6,8,9,11],Lokrisk:[0,1,3,5,6,8,10],'Symmetrisk diminished':[0,2,3,5,6,8,9,11],'Diminished arpeggio':[0,3,6,9],Heltonsskala:[0,2,4,6,8,10],'Lydisk augmented':[0,2,4,6,8,9,11],'Melodisk moll':[0,2,3,5,7,9,11],'Bebop dominant':[0,2,4,5,7,9,10,11]};
function Diagram({c,large=false}:{c:Chord;large?:boolean}){const w=large?230:150,h=large?250:170,l=w*.18,t=h*.18,gw=w*.64,gh=h*.62,base=c.baseFret||1,displayFret=(f:number)=>base>1?f-base+1:f;return <svg viewBox={`0 0 ${w} ${h}`} className={large?'diagram large':'diagram'} role="img" aria-label={`Greppdiagram för ${c.full}`}>{base>1&&<text x={l-(large?18:14)} y={t+gh/10+4} className="base-fret">{base}</text>}{[0,1,2,3,4,5].map(i=><line key={'s'+i} x1={l+i*gw/5} y1={t} x2={l+i*gw/5} y2={t+gh} className="string"/>)}{[0,1,2,3,4,5].map(i=><line key={'f'+i} x1={l} y1={t+i*gh/5} x2={l+gw} y2={t+i*gh/5} className={i?'fret':'nut'}/>)}{c.frets.map((f,i)=>f>0&&<g key={i}><circle cx={l+i*gw/5} cy={t+(displayFret(f)-.5)*gh/5} r={large?11:8}/><text x={l+i*gw/5} y={t+(displayFret(f)-.5)*gh/5+4}>{c.fingers[i]}</text></g>)}{c.frets.map((f,i)=><text key={'o'+i} x={l+i*gw/5} y={t-12} className="mark">{f===0?'○':f<0?'×':''}</text>)}</svg>}
function ScaleFretboard({root,scaleInts,chordInts,activePitch}:{root:number;scaleInts:number[];chordInts:number[];activePitch:number|null}){const strings=[4,11,7,2,9,4],frets=Array.from({length:13},(_,i)=>i),inScale=(pc:number)=>scaleInts.includes((pc-root+12)%12),kind=(pc:number)=>pc===root?'root':chordInts.includes((pc-root+12)%12)?'chord':'scale';return <div className="fretboard-wrap"><div className="fret-legend"><span><i className="root"/>Grundton</span><span><i className="chord"/>Ackordton</span><span><i className="scale"/>Skalton</span></div><div className="fretboard" aria-label="Greppbräda med skalans toner">{strings.map((open,stringIndex)=>frets.map(fret=>{const pc=(open+fret)%12;return <div className={`fret-cell ${fret===0?'open':''}`} key={`${stringIndex}-${fret}`}>{inScale(pc)&&<b className={`${kind(pc)} ${activePitch===pc?'active-tone':''}`}>{noteNames[pc]}</b>}</div>}))}</div><div className="fret-numbers">{frets.map(f=><span key={f}>{f===0?'Öppen':f}</span>)}</div></div>}
const pitch=(f:number)=>((Math.round(12*Math.log2(f/440))+69)%12+12)%12;
const tuningPresets=[
{id:'standard',group:'Vanliga',name:'Standard',hint:'Allround',midis:[40,45,50,55,59,64]},
{id:'drop-d',group:'Vanliga',name:'Drop D',hint:'Rock & metal',midis:[38,45,50,55,59,64]},
{id:'eb',group:'Artist & stil',name:'Halvton ned',hint:'Hendrix / klassisk rock',midis:[39,44,49,54,58,63]},
{id:'d-standard',group:'Vanliga',name:'Helton ned',hint:'Tyngre rock',midis:[38,43,48,53,57,62]},
{id:'drop-c',group:'Artist & stil',name:'Drop C',hint:'Modern metal',midis:[36,43,48,53,57,62]},
{id:'open-g',group:'Öppna',name:'Open G',hint:'Blues & Stones',midis:[38,43,50,55,59,62]},
{id:'keith-g',group:'Artist & stil',name:'Keith Richards 5-strängad',hint:'Open G utan låg E',midis:[43,50,55,59,62]},
{id:'open-d',group:'Öppna',name:'Open D',hint:'Slide, folk & blues',midis:[38,45,50,54,57,62]},
{id:'open-e',group:'Öppna',name:'Open E',hint:'Slide & klassisk rock',midis:[40,47,52,56,59,64]},
{id:'dadgad',group:'Öppna',name:'DADGAD',hint:'Folk & keltiskt',midis:[38,45,50,55,57,62]},
{id:'double-drop-d',group:'Vanliga',name:'Double Drop D',hint:'Singer-songwriter',midis:[38,45,50,55,59,62]},
{id:'baritone-b',group:'Flersträngat',name:'Bariton B-standard',hint:'Baritongitarr',midis:[35,40,45,50,54,59]},
{id:'7-standard',group:'Flersträngat',name:'7-strängad standard',hint:'B–E–A–D–G–B–E',midis:[35,40,45,50,55,59,64]},
{id:'7-drop-a',group:'Flersträngat',name:'7-strängad Drop A',hint:'Modern metal',midis:[33,40,45,50,55,59,64]},
{id:'8-standard',group:'Flersträngat',name:'8-strängad standard',hint:'F#–B–E–A–D–G–B–E',midis:[30,35,40,45,50,55,59,64]},
{id:'8-drop-e',group:'Flersträngat',name:'8-strängad Drop E',hint:'Låg E1',midis:[28,35,40,45,50,55,59,64]},
];
const midiLabel=(m:number)=>pitchNames[((m%12)+12)%12]+(Math.floor(m/12)-1);
export default function Home(){const[selected,setSelected]=useState(chords[0]),[query,setQuery]=useState(''),[theoryRoot,setTheoryRoot]=useState(0),[qualityId,setQualityId]=useState('maj'),[activeScaleIndex,setActiveScaleIndex]=useState(0),[listening,setListening]=useState(false),[soundLoading,setSoundLoading]=useState(false),[selectedString,setSelectedString]=useState(0),[tuningId,setTuningId]=useState('standard'),[repeatTone,setRepeatTone]=useState(false),[detected,setDetected]=useState('—'),[confidence,setConfidence]=useState(0),[level,setLevel]=useState(0),[error,setError]=useState(''),[language,setLanguage]=useState<Language>('sv');const audio=useRef<{ctx:AudioContext;stream:MediaStream;raf:number}|null>(null),soundCtx=useRef<AudioContext|null>(null),guitar=useRef<{play:(note:number,when?:number,options?:Record<string,unknown>)=>unknown}|null>(null);const quality=qualities.find(q=>q.id===qualityId)!;const chordNotes=quality.ints.map(i=>noteNames[(theoryRoot+i)%12]),shownScaleIndex=Math.min(activeScaleIndex,quality.scales.length-1),shownScale=quality.scales[shownScaleIndex],activeTuning=tuningPresets.find(t=>t.id===tuningId)!,copy=getCopy(language);
useEffect(()=>{const saved=window.localStorage.getItem('grepp-language') as Language|null;if(saved&&languages.some(([code])=>code===saved))setLanguage(saved)},[]);
const changeLanguage=(next:Language)=>{setLanguage(next);window.localStorage.setItem('grepp-language',next);document.documentElement.lang=next};
const[activeScalePitch,setActiveScalePitch]=useState<number|null>(null),scaleTimers=useRef<number[]>([]);
const stop=()=>{const a=audio.current;if(a){cancelAnimationFrame(a.raf);a.stream.getTracks().forEach(t=>t.stop());a.ctx.close()}audio.current=null;setListening(false);setLevel(0)};useEffect(()=>()=>stop(),[]);
const stopSound=()=>{const instrument=guitar.current as({stop?:()=>void}|null);instrument?.stop?.();scaleTimers.current.forEach(timer=>window.clearTimeout(timer));scaleTimers.current=[];setActiveScalePitch(null)};
const playChord=async(c:Chord)=>{stop();stopSound();setError('');setSoundLoading(true);try{if(!soundCtx.current)soundCtx.current=new AudioContext();await soundCtx.current.resume();if(!guitar.current){const mod=await import('soundfont-player');guitar.current=await mod.default.instrument(soundCtx.current,'acoustic_guitar_nylon',{soundfont:'FluidR3_GM',format:'mp3',gain:.72})}const tuningMidi=[40,45,50,55,59,64],ctx=soundCtx.current;c.frets.forEach((f,i)=>{if(f>=0)guitar.current?.play(tuningMidi[i]+f,ctx.currentTime+i*.055,{duration:2.8,gain:.82})})}catch{setError('Gitarrljudet kunde inte laddas. Kontrollera internetanslutningen och försök igen.')}finally{setSoundLoading(false)}};
const playScale=async()=>{stop();stopSound();setError('');setSoundLoading(true);try{if(!soundCtx.current)soundCtx.current=new AudioContext();await soundCtx.current.resume();if(!guitar.current){const mod=await import('soundfont-player');guitar.current=await mod.default.instrument(soundCtx.current,'acoustic_guitar_nylon',{soundfont:'FluidR3_GM',format:'mp3',gain:.72})}const ints=scaleIntervals[shownScale]||quality.ints,up=[...ints,12],sequence=[...up,...up.slice(0,-1).reverse()],rootMidi=48+theoryRoot,ctx=soundCtx.current;sequence.forEach((interval,i)=>guitar.current?.play(rootMidi+interval,ctx.currentTime+i*.34,{duration:.75,gain:.8}));const timers=sequence.map((interval,i)=>window.setTimeout(()=>setActiveScalePitch((theoryRoot+interval)%12),i*340));timers.push(window.setTimeout(()=>setActiveScalePitch(null),sequence.length*340));scaleTimers.current=timers}catch{setError('Skalljudet kunde inte laddas. Kontrollera internetanslutningen och försök igen.')}finally{setSoundLoading(false)}};
const playString=async(index:number)=>{stop();stopSound();setSelectedString(index);setError('');setSoundLoading(true);try{if(!soundCtx.current)soundCtx.current=new AudioContext();await soundCtx.current.resume();if(!guitar.current){const mod=await import('soundfont-player');guitar.current=await mod.default.instrument(soundCtx.current,'acoustic_guitar_nylon',{soundfont:'FluidR3_GM',format:'mp3',gain:.72})}guitar.current.play(activeTuning.midis[index],soundCtx.current.currentTime,{duration:4.5,gain:.9})}catch{setError('Referenstonen kunde inte laddas. Kontrollera internetanslutningen och försök igen.')}finally{setSoundLoading(false)}};
useEffect(()=>{if(!repeatTone)return;const timer=window.setInterval(()=>playString(selectedString),4000);return()=>window.clearInterval(timer)},[repeatTone,selectedString,tuningId]);
const start=async()=>{setError('');try{
  const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}}),ctx=new AudioContext();await ctx.resume();
  const an=ctx.createAnalyser();an.fftSize=16384;an.smoothingTimeConstant=.55;ctx.createMediaStreamSource(stream).connect(an);
  const bins=new Float32Array(an.frequencyBinCount),history:number[][]=[];let stableName='',stableFrames=0;setListening(true);
  const run=()=>{an.getFloatFrequencyData(bins);let max=-120;for(let i=8;i<bins.length;i++)if(bins[i]>max)max=bins[i];setLevel(Math.max(0,Math.min(100,(max+72)*2.2)));
    const chroma=Array(12).fill(0),floor=Math.max(-82,max-34);
    for(let i=8;i<bins.length-1;i++){const db=bins[i],f=i*ctx.sampleRate/an.fftSize;if(f>1500)break;if(f>=70&&db>floor&&db>bins[i-1]&&db>=bins[i+1]){const prominence=db-Math.max(bins[i-2]||-120,bins[i+2]||-120);if(prominence>.25)chroma[pitch(f)]+=Math.pow(10,(db-max)/20)*Math.max(.35,prominence)/Math.sqrt(f)}}
    const compressed=chroma.map(v=>Math.sqrt(v)),total=compressed.reduce((a,b)=>a+b,0);
    if(total>.01&&max>-68){const norm=compressed.map(v=>v/total);history.push(norm);if(history.length>12)history.shift();if(history.length>=6){
      const avg=norm.map((_,i)=>history.reduce((s,row)=>s+row[i],0)/history.length),scores=templates.map(([name,notes])=>{const values=notes.map(n=>avg[n]),hit=values.reduce((s,v)=>s+v,0),coverage=values.filter(v=>v>.055).length,outside=1-hit;return{name,coverage,score:hit+Math.min(...values)*1.8+values[0]*.18-outside*.28}}).sort((a,b)=>b.score-a.score),best=scores[0];
      if(best.coverage>=2&&best.score-scores[1].score>.012){if(stableName===best.name)stableFrames++;else{stableName=best.name;stableFrames=1}if(stableFrames>=5){setDetected(best.name);const margin=best.score-scores[1].score;setConfidence(Math.round(Math.min(96,Math.max(50,58+margin*260+best.coverage*7))))}}else stableFrames=0;
    }}const raf=requestAnimationFrame(run);if(audio.current)audio.current.raf=raf};audio.current={ctx,stream,raf:requestAnimationFrame(run)}
}catch{setError('Mikrofonen kunde inte startas. Kontrollera webbläsarens mikrofonbehörighet.')}};
return <main><header className="topbar"><a className="brand" href="#top"><i><Guitar size={22}/></i>Grepp</a><nav><a href="#ackord">{copy.navChords}</a><a href="#teori">{copy.navTheory}</a><a href="#lyssna">{copy.navListen}</a><a href="#stamma">{copy.navTune}</a></nav><div className="header-tools"><label className="language-picker"><span>{copy.language}</span><select value={language} onChange={e=>changeLanguage(e.target.value as Language)} aria-label={copy.language}>{languages.map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label><a className="head-action" href="#lyssna"><Mic size={17}/>{copy.identify}</a></div></header>
<section className="intro" id="top"><div><p className="eyebrow"><Sparkles size={14}/>{copy.eyebrow}</p><h1>{copy.hero}<br/><em>{copy.heroEm}</em></h1></div><p className="lead">{copy.lead}</p></section>
<section className="workspace" id="ackord"><div className="library"><div className="section-head"><div><p className="kicker">{copy.library}</p><h2>{copy.find}</h2></div><span>{chords.length} {copy.chords}</span></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={copy.search}/></label><div className="grid">{chords.filter(c=>(c.name+c.full).toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.name} className={`card ${selected.name===c.name?'active':''}`} onClick={()=>setSelected(c)}><span><b>{c.name}</b><small>{c.full}</small></span><Diagram c={c}/></button>)}</div></div>
<aside className="detail"><p className="kicker">{copy.selected}</p><div className="detail-head"><h2>{selected.name}</h2><span>{selected.full}</span></div><Diagram c={selected} large/><button className="play-chord" onClick={()=>playChord(selected)} disabled={soundLoading}><Volume2 size={18}/>{soundLoading?copy.loadingGuitar:`${copy.listenTo} ${selected.name}`}</button><div className="notes"><span>{copy.tones}</span>{selected.notes.map(n=><b key={n}>{n}</b>)}</div><div className="diagram-guide"><b>{copy.guide}</b><div><span><i>1–4</i>{copy.fingers}</span><span><i>○</i>{copy.open}</span><span><i>×</i>{copy.mute}</span><span><i className="fret-example">3</i>{copy.startFret}</span></div></div><p className="tip">{copy.tip}</p></aside></section>
<section className="theory" id="teori"><div className="theory-intro"><p className="eyebrow"><Music2 size={14}/>{copy.navTheory}</p><h2>{copy.family}<br/><em>{copy.onePlace}</em></h2><p>{formatCopy(copy.theoryIntro,{n:qualities.length,total:12*qualities.length})}</p><div className="selectors"><label>{copy.root}<select value={theoryRoot} onChange={e=>setTheoryRoot(Number(e.target.value))}>{roots.map((r,i)=><option value={i} key={r}>{r}</option>)}</select></label><label>{copy.type}<select value={qualityId} onChange={e=>setQualityId(e.target.value)}>{qualities.map(q=><option value={q.id} key={q.id}>{q.label} ({q.symbol||'dur'})</option>)}</select></label></div></div>
<div className="theory-card"><div className="chord-summary"><span>{copy.selected}</span><strong>{roots[theoryRoot].split(' ')[0]}{quality.symbol}</strong><small>{quality.label}</small></div><div className="tone-row"><span>{copy.chordTones}</span>{chordNotes.map(n=><b key={n}>{n}</b>)}</div><h3>{copy.scales}</h3><div className="scale-list">{quality.scales.map((scale,i)=>{const ints=scaleIntervals[scale]||quality.ints;return <article key={scale} className={shownScaleIndex===i?'selected-scale':''} role="button" tabIndex={0} onClick={()=>setActiveScaleIndex(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveScaleIndex(i)}}}><div><span>0{i+1}</span><h4>{roots[theoryRoot].split(' ')[0]} {scale}</h4></div><p>{ints.map(x=>noteNames[(theoryRoot+x)%12]).join(' · ')}</p><small>{i===0?copy.safe:i===1?copy.color:copy.tension}</small></article>})}</div><div className="fretboard-head"><div><span>{copy.fretboard}</span><h3>{roots[theoryRoot].split(' ')[0]} {shownScale}</h3></div><div className="fretboard-actions"><small>{copy.chooseScale}</small><button className="scale-play" onClick={playScale} disabled={soundLoading}><Volume2 size={16}/>{soundLoading?copy.loadingSound:copy.listenScale}</button></div></div><ScaleFretboard root={theoryRoot} scaleInts={scaleIntervals[shownScale]||quality.ints} chordInts={quality.ints} activePitch={activeScalePitch}/><p className="theory-note">{copy.theoryNote}</p></div></section>
<section className={`listener ${listening?'on':''}`} id="lyssna"><div className="listen-copy"><p className="eyebrow"><Volume2 size={14}/>{copy.recognition}</p><h2>{copy.hear}<br/>{copy.whatPlay}</h2><p>{copy.micInfo}</p><button onClick={listening?stop:start}>{listening?<Square size={19}/>:<Mic size={20}/>} {listening?copy.stop:copy.startMic}</button>{error&&<p className="error">{error}</p>}</div>
<div className="detector" aria-live="polite"><div className="status"><i/><span>{listening?copy.listening:copy.ready}</span><small>{listening?copy.playChord:copy.micOff}</small></div><div className="result"><span>{copy.identified}</span><strong>{detected}</strong><small>{detected==='—'?copy.waiting:`${confidence}${copy.confidence}`}</small></div><div className="meter"><i style={{width:`${level}%`}}/></div><div className="meter-label"><span>{copy.level}</span><span>{Math.round(level)}%</span></div><div className="bars">{[.5,.8,.35,.95,.65,.4,.75,.3,.55,.88,.45,.7].map((v,i)=><i key={i} style={{height:`${Math.max(10,listening?v*level:10)}%`}}/>)}</div></div></section>
<section className="tuner" id="stamma"><div className="tuner-copy"><p className="eyebrow"><Volume2 size={14}/>{copy.tuneRef}</p><h2>{copy.listenCompare}<br/><em>{copy.tuneAfter}</em></h2><p>{copy.tuneInfo}</p><label className="tuning-select">{copy.tuning}<select value={tuningId} onChange={e=>{setTuningId(e.target.value);setSelectedString(0)}}>{['Vanliga','Öppna','Artist & stil','Flersträngat'].map(group=><optgroup label={group} key={group}>{tuningPresets.filter(t=>t.group===group).map(t=><option value={t.id} key={t.id}>{t.name} — {t.hint}</option>)}</optgroup>)}</select></label><label className="repeat-tone"><input type="checkbox" checked={repeatTone} onChange={e=>{setRepeatTone(e.target.checked);if(e.target.checked)playString(selectedString)}}/><span><b>{copy.repeat}</b><small>{copy.everyFour}</small></span></label><button onClick={()=>playString(selectedString)} disabled={soundLoading}><Volume2 size={20}/>{soundLoading?copy.loadingGuitar:copy.playAgain}</button></div><div className="reference-tuner"><div className="reference-head"><span>{activeTuning.name}</span><small>{repeatTone?copy.autoOn:activeTuning.hint}</small></div><div className="reference-note"><span>{copy.selectedString}</span><strong>{midiLabel(activeTuning.midis[selectedString])}</strong><small>{(440*Math.pow(2,(activeTuning.midis[selectedString]-69)/12)).toFixed(2)} Hz</small></div><div className="reference-strings" style={{gridTemplateColumns:`repeat(${activeTuning.midis.length},1fr)`}}>{activeTuning.midis.map((m,i)=><button key={`${m}-${i}`} className={selectedString===i?'selected':''} onClick={()=>playString(i)} disabled={soundLoading}><span>{activeTuning.midis.length-i}</span><strong>{midiLabel(m).replace(/[0-9]/g,'')}</strong><small>{midiLabel(m)}</small><Volume2 size={15}/></button>)}</div><div className="reference-help"><b>{copy.howTune}</b><p>{copy.tuneHelp}</p></div></div></section>
<footer><span><Guitar size={18}/>Grepp</span><p>{copy.built}</p><a className="support-link" href="https://buymeacoffee.com/niacloneq" target="_blank" rel="noreferrer">{copy.support}</a></footer></main>}

