'use client';
import {useEffect,useRef,useState} from 'react';
import {Guitar,Mic,Music2,Search,Sparkles,Square,Volume2} from 'lucide-react';
type Chord={name:string;full:string;frets:number[];fingers:number[];notes:string[]};
const chords:Chord[]=[
{name:'C',full:'C-dur',frets:[-1,3,2,0,1,0],fingers:[0,3,2,0,1,0],notes:['C','E','G']},{name:'G',full:'G-dur',frets:[3,2,0,0,0,3],fingers:[2,1,0,0,0,3],notes:['G','B','D']},{name:'D',full:'D-dur',frets:[-1,-1,0,2,3,2],fingers:[0,0,0,1,3,2],notes:['D','F#','A']},{name:'Am',full:'A-moll',frets:[-1,0,2,2,1,0],fingers:[0,0,2,3,1,0],notes:['A','C','E']},{name:'Em',full:'E-moll',frets:[0,2,2,0,0,0],fingers:[0,2,3,0,0,0],notes:['E','G','B']},{name:'E',full:'E-dur',frets:[0,2,2,1,0,0],fingers:[0,2,3,1,0,0],notes:['E','G#','B']},{name:'A',full:'A-dur',frets:[-1,0,2,2,2,0],fingers:[0,0,1,2,3,0],notes:['A','C#','E']},{name:'F',full:'F-dur',frets:[1,3,3,2,1,1],fingers:[1,3,4,2,1,1],notes:['F','A','C']}];
const pitchNames=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const templates:[string,number[]][]=pitchNames.flatMap((name,root)=>[[name,[root,(root+4)%12,(root+7)%12]],[`${name}m`,[root,(root+3)%12,(root+7)%12]]] as [string,number[]][]);
const roots=['C','C# / Db','D','D# / Eb','E','F','F# / Gb','G','G# / Ab','A','A# / Bb','B'];
const noteNames=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const qualities=[
{id:'maj',label:'Dur',symbol:'',ints:[0,4,7],scales:['Jonisk (dur)','Durpentatonisk','Lydisk']},{id:'min',label:'Moll',symbol:'m',ints:[0,3,7],scales:['Eolisk (naturlig moll)','Mollpentatonisk','Dorisk']},{id:'7',label:'Dominant 7',symbol:'7',ints:[0,4,7,10],scales:['Mixolydisk','Dominant pentatonisk','Altererad (spänning)']},{id:'maj7',label:'Maj 7',symbol:'maj7',ints:[0,4,7,11],scales:['Jonisk (dur)','Lydisk','Durpentatonisk']},{id:'m7',label:'Moll 7',symbol:'m7',ints:[0,3,7,10],scales:['Dorisk','Eolisk','Mollpentatonisk']},{id:'dim',label:'Förminskat',symbol:'dim',ints:[0,3,6],scales:['Hel-halv-diminished','Lokrisk','Symmetrisk diminished']},{id:'dim7',label:'Förminskat 7',symbol:'dim7',ints:[0,3,6,9],scales:['Hel-halv-diminished','Diminished arpeggio']},{id:'aug',label:'Förstorat',symbol:'aug',ints:[0,4,8],scales:['Heltonsskala','Lydisk augmented']},{id:'sus2',label:'Sus 2',symbol:'sus2',ints:[0,2,7],scales:['Jonisk','Mixolydisk','Durpentatonisk']},{id:'sus4',label:'Sus 4',symbol:'sus4',ints:[0,5,7],scales:['Mixolydisk','Jonisk','Durpentatonisk']},{id:'6',label:'Dur 6',symbol:'6',ints:[0,4,7,9],scales:['Jonisk','Durpentatonisk','Lydisk']},{id:'m6',label:'Moll 6',symbol:'m6',ints:[0,3,7,9],scales:['Dorisk','Melodisk moll']},{id:'9',label:'Dominant 9',symbol:'9',ints:[0,4,7,10,2],scales:['Mixolydisk','Bebop dominant']},{id:'maj9',label:'Maj 9',symbol:'maj9',ints:[0,4,7,11,2],scales:['Jonisk','Lydisk']},{id:'m9',label:'Moll 9',symbol:'m9',ints:[0,3,7,10,2],scales:['Dorisk','Eolisk']},{id:'add9',label:'Add 9',symbol:'add9',ints:[0,4,7,2],scales:['Jonisk','Durpentatonisk']},{id:'11',label:'Dominant 11',symbol:'11',ints:[0,4,7,10,2,5],scales:['Mixolydisk','Bebop dominant']},{id:'13',label:'Dominant 13',symbol:'13',ints:[0,4,7,10,2,9],scales:['Mixolydisk','Bebop dominant']}];
const scaleIntervals:Record<string,number[]>={'Jonisk (dur)':[0,2,4,5,7,9,11],Jonisk:[0,2,4,5,7,9,11],Durpentatonisk:[0,2,4,7,9],Lydisk:[0,2,4,6,7,9,11],'Eolisk (naturlig moll)':[0,2,3,5,7,8,10],Eolisk:[0,2,3,5,7,8,10],Mollpentatonisk:[0,3,5,7,10],Dorisk:[0,2,3,5,7,9,10],Mixolydisk:[0,2,4,5,7,9,10],'Dominant pentatonisk':[0,2,4,7,10],'Altererad (spänning)':[0,1,3,4,6,8,10],'Hel-halv-diminished':[0,2,3,5,6,8,9,11],Lokrisk:[0,1,3,5,6,8,10],'Symmetrisk diminished':[0,2,3,5,6,8,9,11],'Diminished arpeggio':[0,3,6,9],Heltonsskala:[0,2,4,6,8,10],'Lydisk augmented':[0,2,4,6,8,9,11],'Melodisk moll':[0,2,3,5,7,9,11],'Bebop dominant':[0,2,4,5,7,9,10,11]};
function Diagram({c,large=false}:{c:Chord;large?:boolean}){const w=large?230:150,h=large?250:170,l=w*.18,t=h*.18,gw=w*.64,gh=h*.62;return <svg viewBox={`0 0 ${w} ${h}`} className={large?'diagram large':'diagram'} role="img" aria-label={`Greppdiagram för ${c.full}`}>{[0,1,2,3,4,5].map(i=><line key={'s'+i} x1={l+i*gw/5} y1={t} x2={l+i*gw/5} y2={t+gh} className="string"/>)}{[0,1,2,3,4,5].map(i=><line key={'f'+i} x1={l} y1={t+i*gh/5} x2={l+gw} y2={t+i*gh/5} className={i?'fret':'nut'}/>)}{c.frets.map((f,i)=>f>0&&<g key={i}><circle cx={l+i*gw/5} cy={t+(f-.5)*gh/5} r={large?11:8}/><text x={l+i*gw/5} y={t+(f-.5)*gh/5+4}>{c.fingers[i]}</text></g>)}{c.frets.map((f,i)=><text key={'o'+i} x={l+i*gw/5} y={t-12} className="mark">{f===0?'○':f<0?'×':''}</text>)}</svg>}
function ScaleFretboard({root,scaleInts,chordInts}:{root:number;scaleInts:number[];chordInts:number[]}){const strings=[4,11,7,2,9,4],frets=Array.from({length:13},(_,i)=>i),inScale=(pc:number)=>scaleInts.includes((pc-root+12)%12),kind=(pc:number)=>pc===root?'root':chordInts.includes((pc-root+12)%12)?'chord':'scale';return <div className="fretboard-wrap"><div className="fret-legend"><span><i className="root"/>Grundton</span><span><i className="chord"/>Ackordton</span><span><i className="scale"/>Skalton</span></div><div className="fretboard" aria-label="Greppbräda med skalans toner">{strings.map((open,stringIndex)=>frets.map(fret=>{const pc=(open+fret)%12;return <div className={`fret-cell ${fret===0?'open':''}`} key={`${stringIndex}-${fret}`}>{inScale(pc)&&<b className={kind(pc)}>{noteNames[pc]}</b>}</div>}))}</div><div className="fret-numbers">{frets.map(f=><span key={f}>{f===0?'Öppen':f}</span>)}</div></div>}
const pitch=(f:number)=>((Math.round(12*Math.log2(f/440))+69)%12+12)%12;
const tuningPresets=[
{id:'standard',group:'Vanliga',name:'Standard',hint:'Allround',midis:[40,45,50,55,59,64]},
{id:'drop-d',group:'Vanliga',name:'Drop D',hint:'Rock & metal',midis:[38,45,50,55,59,64]},
{id:'eb',group:'Artist & stil',name:'Halvton ned',hint:'Hendrix / klassisk rock',midis:[39,44,49,54,58,63]},
{id:'d-standard',group:'Vanliga',name:'Helton ned',hint:'Tyngre rock',midis:[38,43,48,53,57,62]},
{id:'drop-c',group:'Artist & stil',name:'Drop C',hint:'Modern metal',midis:[36,43,48,53,57,62]},
{id:'open-g',group:'Öppna',name:'Open G',hint:'Blues & Stones',midis:[38,43,50,55,59,62]},
{id:'keith-g',group:'Artist & stil',name:'Keith Richards 5-strängad',hint:'Open G utan låg E',midis:[43,50,55,59,62]},
{id:'open-d',group:'Öppna',name:'Open D',hint:'Slide, folk & blues',midis:[38,45,50,54,57,62]},
{id:'open-e',group:'Öppna',name:'Open E',hint:'Slide & klassisk rock',midis:[40,47,52,56,59,64]},
{id:'dadgad',group:'Öppna',name:'DADGAD',hint:'Folk & keltiskt',midis:[38,45,50,55,57,62]},
{id:'double-drop-d',group:'Vanliga',name:'Double Drop D',hint:'Singer-songwriter',midis:[38,45,50,55,59,62]},
{id:'baritone-b',group:'Flersträngat',name:'Bariton B-standard',hint:'Baritongitarr',midis:[35,40,45,50,54,59]},
{id:'7-standard',group:'Flersträngat',name:'7-strängad standard',hint:'B–E–A–D–G–B–E',midis:[35,40,45,50,55,59,64]},
{id:'7-drop-a',group:'Flersträngat',name:'7-strängad Drop A',hint:'Modern metal',midis:[33,40,45,50,55,59,64]},
{id:'8-standard',group:'Flersträngat',name:'8-strängad standard',hint:'F#–B–E–A–D–G–B–E',midis:[30,35,40,45,50,55,59,64]},
{id:'8-drop-e',group:'Flersträngat',name:'8-strängad Drop E',hint:'Låg E1',midis:[28,35,40,45,50,55,59,64]},
];
const midiLabel=(m:number)=>pitchNames[((m%12)+12)%12]+(Math.floor(m/12)-1);
export default function Home(){const[selected,setSelected]=useState(chords[0]),[query,setQuery]=useState(''),[theoryRoot,setTheoryRoot]=useState(0),[qualityId,setQualityId]=useState('maj'),[activeScaleIndex,setActiveScaleIndex]=useState(0),[listening,setListening]=useState(false),[soundLoading,setSoundLoading]=useState(false),[selectedString,setSelectedString]=useState(0),[tuningId,setTuningId]=useState('standard'),[repeatTone,setRepeatTone]=useState(false),[detected,setDetected]=useState('—'),[confidence,setConfidence]=useState(0),[level,setLevel]=useState(0),[error,setError]=useState('');const audio=useRef<{ctx:AudioContext;stream:MediaStream;raf:number}|null>(null),soundCtx=useRef<AudioContext|null>(null),guitar=useRef<{play:(note:number,when?:number,options?:Record<string,unknown>)=>unknown}|null>(null);const quality=qualities.find(q=>q.id===qualityId)!;const chordNotes=quality.ints.map(i=>noteNames[(theoryRoot+i)%12]),shownScaleIndex=Math.min(activeScaleIndex,quality.scales.length-1),shownScale=quality.scales[shownScaleIndex],activeTuning=tuningPresets.find(t=>t.id===tuningId)!;
const stop=()=>{const a=audio.current;if(a){cancelAnimationFrame(a.raf);a.stream.getTracks().forEach(t=>t.stop());a.ctx.close()}audio.current=null;setListening(false);setLevel(0)};useEffect(()=>()=>stop(),[]);
const playChord=async(c:Chord)=>{stop();setError('');setSoundLoading(true);try{if(!soundCtx.current)soundCtx.current=new AudioContext();await soundCtx.current.resume();if(!guitar.current){const mod=await import('soundfont-player');guitar.current=await mod.default.instrument(soundCtx.current,'acoustic_guitar_nylon',{soundfont:'FluidR3_GM',format:'mp3',gain:.72})}const tuningMidi=[40,45,50,55,59,64],ctx=soundCtx.current;c.frets.forEach((f,i)=>{if(f>=0)guitar.current?.play(tuningMidi[i]+f,ctx.currentTime+i*.055,{duration:2.8,gain:.82})})}catch{setError('Gitarrljudet kunde inte laddas. Kontrollera internetanslutningen och försök igen.')}finally{setSoundLoading(false)}};
const playString=async(index:number)=>{stop();setSelectedString(index);setError('');setSoundLoading(true);try{if(!soundCtx.current)soundCtx.current=new AudioContext();await soundCtx.current.resume();if(!guitar.current){const mod=await import('soundfont-player');guitar.current=await mod.default.instrument(soundCtx.current,'acoustic_guitar_nylon',{soundfont:'FluidR3_GM',format:'mp3',gain:.72})}guitar.current.play(activeTuning.midis[index],soundCtx.current.currentTime,{duration:4.5,gain:.9})}catch{setError('Referenstonen kunde inte laddas. Kontrollera internetanslutningen och försök igen.')}finally{setSoundLoading(false)}};
useEffect(()=>{if(!repeatTone)return;const timer=window.setInterval(()=>playString(selectedString),5500);return()=>window.clearInterval(timer)},[repeatTone,selectedString,tuningId]);
const start=async()=>{setError('');try{
  const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}}),ctx=new AudioContext();await ctx.resume();
  const an=ctx.createAnalyser();an.fftSize=16384;an.smoothingTimeConstant=.55;ctx.createMediaStreamSource(stream).connect(an);
  const bins=new Float32Array(an.frequencyBinCount),history:number[][]=[];let stableName='',stableFrames=0;setListening(true);
  const run=()=>{an.getFloatFrequencyData(bins);let max=-120;for(let i=8;i<bins.length;i++)if(bins[i]>max)max=bins[i];setLevel(Math.max(0,Math.min(100,(max+72)*2.2)));
    const chroma=Array(12).fill(0),floor=Math.max(-82,max-34);
    for(let i=8;i<bins.length-1;i++){const db=bins[i],f=i*ctx.sampleRate/an.fftSize;if(f>1500)break;if(f>=70&&db>floor&&db>bins[i-1]&&db>=bins[i+1]){const prominence=db-Math.max(bins[i-2]||-120,bins[i+2]||-120);if(prominence>.25)chroma[pitch(f)]+=Math.pow(10,(db-max)/20)*Math.max(.35,prominence)/Math.sqrt(f)}}
    const compressed=chroma.map(v=>Math.sqrt(v)),total=compressed.reduce((a,b)=>a+b,0);
    if(total>.01&&max>-68){const norm=compressed.map(v=>v/total);history.push(norm);if(history.length>12)history.shift();if(history.length>=6){
      const avg=norm.map((_,i)=>history.reduce((s,row)=>s+row[i],0)/history.length),scores=templates.map(([name,notes])=>{const values=notes.map(n=>avg[n]),hit=values.reduce((s,v)=>s+v,0),coverage=values.filter(v=>v>.055).length,outside=1-hit;return{name,coverage,score:hit+Math.min(...values)*1.8+values[0]*.18-outside*.28}}).sort((a,b)=>b.score-a.score),best=scores[0];
      if(best.coverage>=2&&best.score-scores[1].score>.012){if(stableName===best.name)stableFrames++;else{stableName=best.name;stableFrames=1}if(stableFrames>=5){setDetected(best.name);const margin=best.score-scores[1].score;setConfidence(Math.round(Math.min(96,Math.max(50,58+margin*260+best.coverage*7))))}}else stableFrames=0;
    }}const raf=requestAnimationFrame(run);if(audio.current)audio.current.raf=raf};audio.current={ctx,stream,raf:requestAnimationFrame(run)}
}catch{setError('Mikrofonen kunde inte startas. Kontrollera webbläsarens mikrofonbehörighet.')}};
return <main><header className="topbar"><a className="brand" href="#top"><i><Guitar size={22}/></i>Grepp</a><nav><a href="#ackord">Grepp</a><a href="#teori">Ackord & skalor</a><a href="#lyssna">Lyssna</a><a href="#stamma">Stäm</a></nav><a className="head-action" href="#lyssna"><Mic size={17}/>Identifiera ackord</a></header>
<section className="intro" id="top"><div><p className="eyebrow"><Sparkles size={14}/>Din digitala ackordbok</p><h1>Spela. Lyssna.<br/><em>Lär dig.</em></h1></div><p className="lead">Utforska gitarrackord, lär dig greppen och låt mikrofonen hjälpa dig höra vad du spelar.</p></section>
<section className="workspace" id="ackord"><div className="library"><div className="section-head"><div><p className="kicker">Ackordbibliotek</p><h2>Hitta ditt ackord</h2></div><span>{chords.length} ackord</span></div><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sök ackord, t.ex. Am"/></label><div className="grid">{chords.filter(c=>(c.name+c.full).toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.name} className={`card ${selected.name===c.name?'active':''}`} onClick={()=>setSelected(c)}><span><b>{c.name}</b><small>{c.full}</small></span><Diagram c={c}/></button>)}</div></div>
<aside className="detail"><p className="kicker">Valt ackord</p><div className="detail-head"><h2>{selected.name}</h2><span>{selected.full}</span></div><Diagram c={selected} large/><button className="play-chord" onClick={()=>playChord(selected)} disabled={soundLoading}><Volume2 size={18}/>{soundLoading?'Laddar gitarrljud…':`Lyssna på ${selected.name}`}</button><div className="notes"><span>Toner</span>{selected.notes.map(n=><b key={n}>{n}</b>)}</div><p className="tip">Tryck med fingertoppen nära bandstaven. Spela strängarna långsamt och lyssna efter en ren ton.</p></aside></section>
<section className="theory" id="teori"><div className="theory-intro"><p className="eyebrow"><Music2 size={14}/>Ackord & skalor</p><h2>Hela ackordfamiljen.<br/><em>På ett ställe.</em></h2><p>Välj grundton och ackordtyp. Biblioteket omfattar 12 grundtoner × {qualities.length} ackordtyper — totalt {12*qualities.length} ackord — med toninnehåll och användbara skalval.</p><div className="selectors"><label>Grundton<select value={theoryRoot} onChange={e=>setTheoryRoot(Number(e.target.value))}>{roots.map((r,i)=><option value={i} key={r}>{r}</option>)}</select></label><label>Ackordtyp<select value={qualityId} onChange={e=>setQualityId(e.target.value)}>{qualities.map(q=><option value={q.id} key={q.id}>{q.label} ({q.symbol||'dur'})</option>)}</select></label></div></div>
<div className="theory-card"><div className="chord-summary"><span>Valt ackord</span><strong>{roots[theoryRoot].split(' ')[0]}{quality.symbol}</strong><small>{quality.label}</small></div><div className="tone-row"><span>Ackordtoner</span>{chordNotes.map(n=><b key={n}>{n}</b>)}</div><h3>Skalor som passar</h3><div className="scale-list">{quality.scales.map((scale,i)=>{const ints=scaleIntervals[scale]||quality.ints;return <article key={scale} className={shownScaleIndex===i?'selected-scale':''} role="button" tabIndex={0} onClick={()=>setActiveScaleIndex(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveScaleIndex(i)}}}><div><span>0{i+1}</span><h4>{roots[theoryRoot].split(' ')[0]} {scale}</h4></div><p>{ints.map(x=>noteNames[(theoryRoot+x)%12]).join(' · ')}</p><small>{i===0?'Tryggt förstaval — innehåller ackordtonerna tydligt.':i===1?'Ger en annan färg men behåller stabila måltoner.':'Mer färg och spänning — använd med örat.'}</small></article>})}</div><div className="fretboard-head"><div><span>Greppbräda</span><h3>{roots[theoryRoot].split(' ')[0]} {shownScale}</h3></div><small>Klicka på en skala ovan för att byta</small></div><ScaleFretboard root={theoryRoot} scaleInts={scaleIntervals[shownScale]||quality.ints} chordInts={quality.ints}/><p className="theory-note">Skalval beror också på låtens tonart och ackordet före och efter. Använd ackordtonerna som landningspunkter.</p></div></section>
<section className={`listener ${listening?'on':''}`} id="lyssna"><div className="listen-copy"><p className="eyebrow"><Volume2 size={14}/>Ackordigenkänning</p><h2>Låt oss höra<br/>vad du spelar.</h2><p>Ge mikrofonåtkomst och slå an ett ackord tydligt. Analysen sker direkt på din enhet — inget ljud sparas.</p><button onClick={listening?stop:start}>{listening?<Square size={19}/>:<Mic size={20}/>} {listening?'Stoppa lyssning':'Starta mikrofonen'}</button>{error&&<p className="error">{error}</p>}</div>
<div className="detector" aria-live="polite"><div className="status"><i/><span>{listening?'Lyssnar nu':'Redo att lyssna'}</span><small>{listening?'Spela ett ackord':'Mikrofon av'}</small></div><div className="result"><span>Identifierat ackord</span><strong>{detected}</strong><small>{detected==='—'?'Väntar på ljud…':`${confidence}% säkerhet`}</small></div><div className="meter"><i style={{width:`${level}%`}}/></div><div className="meter-label"><span>Ljudnivå</span><span>{Math.round(level)}%</span></div><div className="bars">{[.5,.8,.35,.95,.65,.4,.75,.3,.55,.88,.45,.7].map((v,i)=><i key={i} style={{height:`${Math.max(10,listening?v*level:10)}%`}}/>)}</div></div></section>
<section className="tuner" id="stamma"><div className="tuner-copy"><p className="eyebrow"><Volume2 size={14}/>Stäm med referenston</p><h2>Lyssna. Jämför.<br/><em>Stäm efter tonen.</em></h2><p>Välj stämning och sträng. Spela samma sträng på gitarren och justera tills tonerna smälter samman utan tydliga svävningar.</p><label className="tuning-select">Stämning<select value={tuningId} onChange={e=>{setTuningId(e.target.value);setSelectedString(0)}}>{['Vanliga','Öppna','Artist & stil','Flersträngat'].map(group=><optgroup label={group} key={group}>{tuningPresets.filter(t=>t.group===group).map(t=><option value={t.id} key={t.id}>{t.name} — {t.hint}</option>)}</optgroup>)}</select></label><label className="repeat-tone"><input type="checkbox" checked={repeatTone} onChange={e=>{setRepeatTone(e.target.checked);if(e.target.checked)playString(selectedString)}}/><span><b>Upprepa tonen</b><small>Spelar automatiskt var 5,5 sekund</small></span></label><button onClick={()=>playString(selectedString)} disabled={soundLoading}><Volume2 size={20}/>{soundLoading?'Laddar gitarrljud…':'Spela tonen igen'}</button></div><div className="reference-tuner"><div className="reference-head"><span>{activeTuning.name}</span><small>{repeatTone?'Automatisk upprepning på':activeTuning.hint}</small></div><div className="reference-note"><span>Vald sträng</span><strong>{midiLabel(activeTuning.midis[selectedString])}</strong><small>{(440*Math.pow(2,(activeTuning.midis[selectedString]-69)/12)).toFixed(2)} Hz</small></div><div className="reference-strings" style={{gridTemplateColumns:`repeat(${activeTuning.midis.length},1fr)`}}>{activeTuning.midis.map((m,i)=><button key={`${m}-${i}`} className={selectedString===i?'selected':''} onClick={()=>playString(i)} disabled={soundLoading}><span>{activeTuning.midis.length-i}</span><strong>{midiLabel(m).replace(/[0-9]/g,'')}</strong><small>{midiLabel(m)}</small><Volume2 size={15}/></button>)}</div><div className="reference-help"><b>Så hör du att det stämmer</b><p>När tonerna ligger nära varandra hörs ett pulserande ljud. Skruva försiktigt tills pulseringen saktar ned och försvinner.</p></div></div></section>
<footer><span><Guitar size={18}/>Grepp</span><p>Byggd för nyfikna gitarrister.</p></footer></main>}

